### ISSUE TITLE
ellipsis bug

### ISSUE THREAD

**Issue by increpare** [bvoq/mixedaim#12]
I can't solve the first level of this in puzzlescriptmis - do you require "..." in ellipses to be a gap or not? (It seems like it doesn't let "[ player | ... | fruit ]" match "[player|fruit]", which it does in vanilla puzzlescript )

https://www.puzzlescript.net/play.html?p=17e594967677a04014fe32126e2dacea

**Comment by bvoq** [comment]
Thank you. The issue is an off-by-one in the corners to the right. For now adding a border of size 1 should be a workaround. Will publish changes with the next round of fixes.

**Comment by bvoq** [comment]
fixed in new version
