### ISSUE TITLE
difficulty under thumbnail not the same as difficulty under level preview?

### ISSUE THREAD

**Issue by increpare** [bvoq/mixedaim#13]
![image](https://user-images.githubusercontent.com/465632/124324522-6369aa00-db83-11eb-811c-b055396ce924.png)

Also note that the two left levels have teh same shape but different displayed difficulties.

the source code is 

https://www.puzzlescript.net/editor.html?hack=14095d52798985ebfcbf2a52af80ac9d

the transformation code is:

```
==========
TRANSFORM
==========
choose 1 option 0.5 [ no player no fruit ] -> [fruit]
```

**Comment by bvoq** [comment]
This can happen due to race conditions and the way the tool stops solving.
