### ISSUE TITLE
crash with invalid transformation rule

### ISSUE THREAD

**Issue by increpare** [bvoq/mixedaim#15]
https://www.puzzlescript.net/editor.html?hack=144492cb2a9d461d670ff41d1d704e11

Crashes during transformation.  It has the invalid transformation rule

"choose 3 option 0.5 [ crate1 | no wall no nospawn no player no crate ] -> [ crate | crate1 ]"

(crate is defined as being either "crate1 or crate2", so this should get flagged as incorrect because its ambiguous right?)

At least I assume that's the reason it's crashing. Maybe there's some other reason 

(edit: updated with simpler example)

**Comment by bvoq** [comment]
fixed in 1.3
