### ISSUE TITLE
difference in puzzlescript vs puzzlescriptmis behaviour

### ISSUE THREAD

**Issue by increpare** [bvoq/mixedaim#20]
in this example I can move around in the first level in puzzlescript, but when I try to play it in puzzlescript+mis I can't move
https://www.puzzlescript.net/editor.html?hack=abe0f86680a6476a52935dca9f595599

**Comment by bvoq** [comment]
I don't understand, isn't puzzlescript+mis doing the right behaviour here?
It's reading the late rules from top to bottom?
Or have you merged all late rules into one big rule?

**Comment by increpare** [comment]
I'm not sure what you mean.  Late rules should basically work the same as normie rules.  Let me say what exactly the current code does, and you can tell me where your interpretation differs :)

=========================

Turn starts with everyone moving right!

![image](https://user-images.githubusercontent.com/465632/129077889-71fa5510-a415-4b94-b48b-6b424de428b3.png)

```[player]->[player beforepos ]```
This puts tags (Red dots) on the player's position at the start of the turn.

![image](https://user-images.githubusercontent.com/465632/129077940-b6eb54f8-c5cb-481d-9e3d-fe6c99468514.png)

[movement processing happens]

![image](https://user-images.githubusercontent.com/465632/129077983-152b3337-467c-40d1-b461-4a00fc23b29c.png)

```late [ beforepos no player ] [ beforepos player ] -> [ beforepos ] [ player ]````
After movement-processing, if there is a tag not on the player, remove all tags from the player.

![image](https://user-images.githubusercontent.com/465632/129078018-18710067-8440-4659-a177-754f09baee1c.png)

late [ beforepos player ] -> cancel
If a tag remains on the player (that is, if the above line never got triggered), cancel the turn

[doesn't get triggered]

late [beforepos]->[]
remove all tags.

![image](https://user-images.githubusercontent.com/465632/129078059-926cc60d-daeb-4652-b4a8-28b114073f84.png)

**Comment by bvoq** [comment]
Aha! It's actually the same bug with how the movement replacement is done. 

```
[player]->[player beforepos ]
```

this rule alone already removes all the movements!
