### ISSUE TITLE
startloop/endloop error?

### ISSUE THREAD

**Issue by increpare** [bvoq/mixedaim#23]
load up the first level of https://www.puzzlescript.net/editor.html?hack=f07e8d42c417c3d168c5a7c44995461d and press left. 
in puzzlscript.net you get

![image](https://user-images.githubusercontent.com/465632/128852520-8cd0d389-54c3-42bc-8cf0-281b96858c57.png)

in puzzlescriptmis you get

![image](https://user-images.githubusercontent.com/465632/128852432-c9d32028-c63a-4e13-a80c-34c42f5daa0d.png)

edit: i simplified the example a bit further removing some unnecessary rules so the screen isn't exactly how it looks like anymore, but the behaviour is still different in both versions.

[ edit edit: I did find a workaround for the game this example comes from ]

**Comment by bvoq** [comment]
Added startloop/endloop with upcoming version.
