### ISSUE TITLE
bug / inconsistent behaviour

### ISSUE THREAD

**Issue by increpare** [bvoq/mixedaim#24]
https://www.puzzlescript.net/editor.html?hack=c40a72cbaaedcd302ace9c4e57ba7b02

in puzzlescript.net you can move freely in the level, in puzzlescriptmis you can't move at all. 

(was trying to implement a workaround to require_player_movement and this happened, leaving me scratching my head a bit ^^ [edit: but I did find a workaround for my case] )

**Comment by bvoq** [comment]
Again this is really weird to me.

```
[player]->[player oldplayerpos ]
late [ player oldplayerpos]->cancel
late [oldplayerpos]->[]
```

obviously the late rule is triggered at all times no?

**Comment by increpare** [comment]
essentially a dupe of https://github.com/bvoq/puzzlescriptmis/issues/20, right?
