### ISSUE TITLE
game behaves differently in puzzlescriptmis vs vanilla

### ISSUE THREAD

**Issue by increpare** [bvoq/mixedaim#29]
See the first level here, and try move

https://www.puzzlescript.net/editor.html?hack=88fe905cf39063e8b23fd6e1683fb82e

it look slike this:

![image](https://user-images.githubusercontent.com/465632/131686572-1787981c-47d5-48d7-ba3b-4ccd7106d946.png)

if you do this in puzzlescript mis (+ move a bit) it looks like this:

![image](https://user-images.githubusercontent.com/465632/131686488-5421d7e9-5343-4669-be59-0e6a8a1bd8f3.png)

The example game is super complicated and I didn't have the energy to prepare a proper test case, but I figure it was worth mentioning anyway - maybe I'll have energy in the future to make a proper test-case for you.

(my guess is that it has something to do with loops, possibly related to #23 )

**Comment by bvoq** [comment]
<img width="624" alt="image" src="https://github.com/bvoq/puzzlescriptmis/assets/3169217/3ab13711-26c8-49ef-bef7-b8a4b5eb7ddf">

Startloop/endloop wasn't implemented before. Now it is!
