### ISSUE TITLE
why are the difficulties different?

### ISSUE THREAD

**Issue by increpare** [bvoq/mixedaim#8]
I took the standard microban project ( [ >  Player ] [ Crate ] -> [  >  Player ] [ > Crate  ] ) and I'm wondering why there are different difficulties reported for essentially equal levels?
![image](https://user-images.githubusercontent.com/465632/124298886-15da4680-db5d-11eb-8ac4-0e1456d5251d.png)

Is it a bug? Or an artefact of RNG?

**Comment by bvoq** [comment]
artefact of RNG in the sense that each level is solved with 3 solvers simultaneously and the first one to solve it, that's the difficulty it gets. there is a race condition there.
